language: java

before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
install: mvn dependency:resolve dependency:resolve-plugins
before_script: java -version
script: mvn clean verify

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      after_success: mvn jacoco:report
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: oraclejdk11
    - jdk: openjdk11
    - jdk: openjdk12
    - jdk: openjdk13
    - jdk: openjdk-ea

  allow_failures:
    - jdk: openjdk-ea

